# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_category_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='章节')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'db_table': 't_chapter',
                'verbose_name_plural': '章节',
                'ordering': ['publish_date'],
                'verbose_name': '章节',
            },
        ),
        migrations.CreateModel(
            name='RollSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('free', models.IntegerField(choices=[(0, '免费'), (1, 'VIP')], default=0, verbose_name='免费级别')),
            ],
            options={
                'db_table': 't_roll',
                'verbose_name_plural': '卷集',
                'ordering': ['id'],
                'verbose_name': '卷集',
            },
        ),
        migrations.AddField(
            model_name='art',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='arts', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='rollset',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Art', verbose_name='所属文章'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='rool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.RollSet', verbose_name='所属卷集'),
        ),
    ]
