# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 05:51
from __future__ import unicode_literals

import art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_auto_20180829_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=art.models.save_file_path, verbose_name='封面'),
        ),
    ]
